### ISSUE TITLE
Heartbeat Decoder Output Error for failedTransmissionBeforeRejoinConfig

### ISSUE THREAD

**Issue by EVPavlo** [VolleyBoast/Decoder#6]
Decoding a heartbeat payload in the customer portal tools.
The result is inaccurate regarding Failed Transmissions before Rejoin.

![Screen Shot 2022-11-01 at 1 31 47 PM](https://user-images.githubusercontent.com/106605305/199311530-60cbb747-4aca-4c88-9f0e-e3ce86698125.png)

The correct result from the VoBo Serial Output:
```
Sending Heartbeat message.
[INFO] Logs: 35
[INFO] ADC Battery Voltage=892
[INFO] Firmware Version Major=1
[INFO] Firmware Version Minor=3
[INFO] Firmware Version Patch=10
[INFO] Firmware Version Custom=0
[INFO] Received Signal Levels=72
[INFO] Analog Voltage Config=12
[INFO] Analog Power Time Config=10
[INFO] Failed Transmissions Before Rejoin Config=10
[INFO] Cycle Through FSB=1
[INFO] Ack Frequency=4
[INFO] Ack Request=2
[INFO] Ack Enable=1
[INFO] Size=11
[INFO] Set app port to [10]
```
Along with the result from the most recent decoder:
```
❯ node ./Decoder.js
{
  batteryLevelMV: 3568,
  fwVersionMajor: 1,
  fwVersionMinor: 3,
  fwVersionPatch: 10,
  fwVersionCustom: 0,
  recSignalLevels: -72,
  analogVoltageConfig: 12,
  analogPowerTimeConfig: 1,
  failedTransmissionBeforeRejoinConfig: 10,
  cycleThroughFSB: 1,
  ackEnable: 1,
  ackFreq: 4,
  ackReq: 2
}                        
```
Most Recent Decoder Commit: ab7593dbcee060ce881a31b511600394bdbd4c29

**Comment by anubala107** [comment]
checking

**Comment by Garviles** [comment]
Tested new Customer Portal Dev Decoder (10) - Shows correct values. Will continue to check other payloads (1-9) for correct values.

**Comment by Garviles** [comment]
This is related to issue #55 so I will close this issue, and we will continue on the other issue.
